"""Report models for Hilbert."""

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field


class Report(BaseModel):
    """Research report generated by Hilbert."""

    report_id: str
    title: str
    query: str
    executive_summary: str = ""
    sections: dict[str, str] = Field(default_factory=dict)
    sources: list[dict] = Field(default_factory=list)
    findings_summary: list[dict] = Field(default_factory=list)
    bibliography: str = ""
    created_at: datetime = Field(default_factory=datetime.now)
    status: str = "draft"  # draft, final

    def to_markdown(self) -> str:
        """Export report as Markdown."""
        lines = [
            f"# {self.title}",
            "",
            f"**Query:** {self.query}",
            f"**Date:** {self.created_at.strftime('%Y-%m-%d')}",
            "",
        ]

        if self.executive_summary:
            lines.extend(["## Executive Summary", self.executive_summary, ""])

        for section_name, section_content in self.sections.items():
            lines.extend([f"## {section_name}", section_content, ""])

        if self.findings_summary:
            lines.append("## Findings Summary")
            for f in self.findings_summary:
                conf = f.get("confidence", 0.0)
                label = f.get("confidence_label", "unverified")
                lines.append(f"- {f.get('claim', '')} [{label}: {conf:.2f}]")

        if self.sources:
            lines.append("## Sources")
            for i, src in enumerate(self.sources, 1):
                title = src.get("title", "Unknown")
                authors = src.get("authors", [])
                year = src.get("published_date", "n.d.")
                url = src.get("url", "")
                lines.append(f"{i}. {title}, {' et al.' if len(authors) > 2 else ', '.join(authors[:2])} ({year}). {url}")

        return "\n".join(lines)

    def to_json(self) -> dict:
        """Export report as JSON-serializable dict."""
        return {
            "report_id": self.report_id,
            "title": self.title,
            "query": self.query,
            "executive_summary": self.executive_summary,
            "sections": self.sections,
            "sources": self.sources,
            "findings_summary": self.findings_summary,
            "created_at": self.created_at.isoformat(),
            "status": self.status,
        }

    def to_bibtex(self) -> str:
        """Export bibliography as BibTeX."""
        return self.bibliography