"""Report models for Hilbert."""

from datetime import datetime
from typing import Dict, List, Optional
from pydantic import BaseModel, Field


class Report(BaseModel):
    """Research report generated by Hilbert."""

    report_id: str
    title: str
    query: str
    executive_summary: str = ""
    sections: Dict[str, str] = Field(default_factory=dict)
    sources: List[dict] = Field(default_factory=list)
    # Mapping from source number (1-based str) to paper_id for inline [N] references
    source_index: Dict[str, str] = Field(default_factory=dict)
    findings_summary: List[dict] = Field(default_factory=list)
    bibliography: str = ""
    created_at: datetime = Field(default_factory=datetime.now)
    status: str = "draft"  # draft, final

    def to_markdown(self) -> str:
        """Export report as Markdown with inline [N] citation support."""
        lines = [
            f"# {self.title}",
            "",
            f"**Query:** {self.query}",
            f"**Date:** {self.created_at.strftime('%Y-%m-%d')}",
            "",
        ]

        if self.executive_summary:
            lines.extend(["## Executive Summary", self.executive_summary, ""])

        for section_name, section_content in self.sections.items():
            lines.extend([f"## {section_name.title()}", section_content, ""])

        if self.findings_summary:
            lines.extend(["## Key Findings", ""])
            for f in self.findings_summary:
                conf = f.get("confidence", 0.0)
                label = f.get("confidence_label", "unverified")
                verified_icon = "✓" if f.get("is_verified") else "○"
                lines.append(
                    f"- {verified_icon} {f.get('claim', '')} "
                    f"*(confidence: {conf:.2f}, {label})*"
                )
            lines.append("")

        if self.sources:
            lines.extend(["## References", ""])
            for i, src in enumerate(self.sources, 1):
                title = src.get("title", "Unknown")
                authors = src.get("authors", [])
                year = src.get("published_date", "n.d.")
                url = src.get("url", "")
                doi = src.get("doi", "")

                if isinstance(authors, list):
                    author_str = (
                        ", ".join(str(a) for a in authors[:2])
                        + (" et al." if len(authors) > 2 else "")
                    )
                else:
                    author_str = str(authors)

                ref = f"[{i}] {author_str} ({year}). *{title}*."
                if doi:
                    ref += f" https://doi.org/{doi}"
                elif url:
                    ref += f" {url}"
                lines.append(ref)

        return "\n".join(lines)

    def to_json(self) -> dict:
        """Export report as JSON-serializable dict."""
        return {
            "report_id": self.report_id,
            "title": self.title,
            "query": self.query,
            "executive_summary": self.executive_summary,
            "sections": self.sections,
            "sources": self.sources,
            "source_index": self.source_index,
            "findings_summary": self.findings_summary,
            "created_at": self.created_at.isoformat(),
            "status": self.status,
        }

    def to_bibtex(self) -> str:
        """Export bibliography as BibTeX."""
        return self.bibliography